---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Smart Response App"
  contact: {}
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9000"
basePath: "/api/v1"
schemes:
- https
paths:
  /auth:
    post:
      summary: "Request Auth Token"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AuthRequest"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/AuthKey"
        400:
          description: "Sehr unerfräulicher Fall! Bei korrekter Installation nicht\
            \ möglich. Gut loggen und Admin bescheid geben"
  /last_ticket:
    get:
      summary: "Get My Requests"
      parameters:
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Ticket Id or Empty"
          schema:
            $ref: "#/definitions/ApiTicket"
        204:
          description: "No Last Ticket exists"
        401:
          description: "Status 401"
  /tickets:
    post:
      summary: "Create new SupportRequest"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ApiTicketInfo"
      responses:
        200:
          description: "Returns the saved Ticket"
          schema:
            $ref: "#/definitions/ApiTicket"
  /tickets/{ticketId}:
    put:
      summary: "Updates a Ticket"
      consumes:
      - "application/json"
      parameters:
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      - name: "ticketId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ApiTicketInfo"
      responses:
        204:
          description: "Status 204"
        401:
          description: "Status 401"
  /tickets/{ticketId}/media:
    post:
      summary: "Add Media"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "ticketId"
        in: "path"
        required: true
        type: "string"
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      - name: "media"
        in: "formData"
        required: true
        type: "file"
      responses:
        204:
          description: "Status 204"
        401:
          description: "Status 401"
  /me:
    get:
      summary: "Get My Information"
      description: "returns the information for the current user"
      produces:
      - "application/json"
      parameters:
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/UserData"
        401:
          description: "Status 401"
    put:
      summary: "Change my Information"
      consumes:
      - "application/json"
      parameters:
      - name: "authkey"
        in: "query"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        204:
          description: "Status 204"
        400:
          description: "Server geupdated, Client nicht z.B., Übertragungsfehler??\
            \ Bug durch Emojis oder ähnlichem?\n\nRohdaten logen, info an  Recordbay\
            \ / Admin"
        401:
          description: "Status 401"
definitions:
  ApiTicketInfo:
    type: "object"
    required:
    - "closed"
    properties:
      timeslot:
        type: "string"
        format: "date-time"
        description: "time for callback"
      telephone:
        type: "string"
      closed:
        type: "boolean"
        default: false
  ApiTicket:
    type: "object"
    required:
    - "closed"
    - "key"
    - "media"
    properties:
      timeslot:
        type: "string"
        format: "date-time"
        description: "time for callback"
      telephone:
        type: "string"
      closed:
        type: "boolean"
        default: false
      key:
        type: "string"
      media:
        type: "array"
        items:
          type: "string"
  UserData:
    type: "object"
    required:
    - "email"
    - "telephone"
    properties:
      telephone:
        type: "array"
        items:
          $ref: "#/definitions/TelephoneNumber"
      firstname:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
  AuthRequest:
    type: "object"
    required:
    - "password"
    - "userkey"
    properties:
      userkey:
        type: "string"
      password:
        type: "string"
  AuthKey:
    type: "object"
    required:
    - "key"
    properties:
      key:
        type: "string"
  TelephoneNumber:
    type: "object"
    required:
      - "number"
      - "assistant"
    properties:
      number:
        type: "string"
      assistant:
        type: "boolean"
